import { useState } from "react";
import Sidebar from "../components/Sidebar";
import api from "../services/api";
import toast from "react-hot-toast";
import { Brain, Send, ArrowRight } from "lucide-react";

function Interview() {
  const [jobDescription, setJobDescription] = useState("");
  const [questions, setQuestions] = useState([]);
  const [current, setCurrent] = useState(0);

  const [answer, setAnswer] = useState("");
  const [result, setResult] = useState(null);

  const [loading, setLoading] = useState(false);
  const [evaluating, setEvaluating] = useState(false);

  const startInterview = async () => {
    if (!jobDescription.trim()) {
      toast.error("Enter a Job Description");
      return;
    }

    try {
      setLoading(true);

      const res = await api.post("/interview/start", {
        job_description: jobDescription,
      });

      setQuestions(res.data.questions);
      setCurrent(0);
      setAnswer("");
      setResult(null);

      toast.success("Interview Started");
    } catch (err) {
      console.error(err);

      toast.error(
        err.response?.data?.detail ||
          "Unable to start interview."
      );
    } finally {
      setLoading(false);
    }
  };

  const submitAnswer = async () => {
    if (!answer.trim()) {
      toast.error("Please enter your answer.");
      return;
    }

    try {
      setEvaluating(true);

      const res = await api.post("/interview/answer", {
        interview_id: questions[current].id,
        answer: answer,
      });

      setResult(res.data);

      toast.success("Answer Evaluated");
    } catch (err) {
      console.error(err);

      toast.error(
        err.response?.data?.detail ||
          "Evaluation failed."
      );
    } finally {
      setEvaluating(false);
    }
  };

  const nextQuestion = () => {
    setCurrent(current + 1);
    setAnswer("");
    setResult(null);
  };

  const finishInterview = async () => {
    try {
      const res = await api.get("/interview/report");

      console.log(res.data);

      toast.success(
        `Interview Finished!\nAverage Score: ${res.data.average_score}/10`
      );
    } catch (err) {
      console.error(err);
    }
  };
    return (
    <div className="flex min-h-screen bg-slate-100">
      <Sidebar />

      <div className="flex-1 p-8">

        <div className="bg-gradient-to-r from-purple-700 via-indigo-700 to-blue-700 rounded-3xl p-8 text-white shadow-xl mb-8">

          <div className="flex items-center gap-4">

            <Brain size={45} />

            <div>
              <h1 className="text-4xl font-bold">
                AI Mock Interview
              </h1>

              <p className="text-purple-100 mt-2">
                Practice interview questions generated by AI.
              </p>
            </div>

          </div>

        </div>

        {questions.length === 0 ? (

          <div className="bg-white rounded-2xl shadow-lg p-8">

            <h2 className="text-2xl font-bold mb-4">
              Start Interview
            </h2>

            <textarea
              rows={10}
              value={jobDescription}
              onChange={(e) =>
                setJobDescription(e.target.value)
              }
              placeholder="Paste the Job Description here..."
              className="w-full border rounded-xl p-4"
            />

            <button
              onClick={startInterview}
              disabled={loading}
              className="mt-5 bg-blue-600 hover:bg-blue-700 text-white px-8 py-3 rounded-xl"
            >
              {loading ? "Generating..." : "Start Interview"}
            </button>

          </div>

        ) : (

          <div className="space-y-6">

            <div className="bg-white rounded-2xl shadow-lg p-8">

              <div className="flex justify-between">

                <h2 className="text-xl font-bold">
                  Question {current + 1} / {questions.length}
                </h2>

                <span className="text-blue-600 font-semibold">
                  AI Generated
                </span>

              </div>

              <div className="mt-6 bg-slate-100 rounded-xl p-6 text-lg">

                {questions[current].question}

              </div>

            </div>

            <div className="bg-white rounded-2xl shadow-lg p-8">

              <h2 className="text-xl font-bold mb-4">
                Your Answer
              </h2>

              <textarea
                rows={8}
                value={answer}
                onChange={(e) => setAnswer(e.target.value)}
                className="w-full border rounded-xl p-4"
                placeholder="Type your answer..."
              />

              <button
                onClick={submitAnswer}
                disabled={evaluating}
                className="mt-5 bg-green-600 hover:bg-green-700 text-white px-8 py-3 rounded-xl flex items-center gap-2"
              >
                <Send size={18} />
                {evaluating ? "Evaluating..." : "Submit Answer"}
              </button>

            </div>

            {result && (

              <div className="bg-white rounded-2xl shadow-lg p-8">

                <h2 className="text-2xl font-bold mb-4">
                  AI Feedback
                </h2>

                <div className="mb-4">

                  <span className="font-bold">
                    Score:
                  </span>{" "}

                  <span className="text-blue-600 text-xl font-bold">
                    {result.score}/10
                  </span>

                </div>

                <pre className="whitespace-pre-wrap text-gray-700">
                  {result.feedback}
                </pre>

                {current < questions.length - 1 ? (

                  <button
                    onClick={nextQuestion}
                    className="mt-6 bg-blue-600 hover:bg-blue-700 text-white px-8 py-3 rounded-xl flex items-center gap-2"
                  >
                    Next Question
                    <ArrowRight size={18} />
                  </button>

                ) : (

                  <button
                    onClick={finishInterview}
                    className="mt-6 bg-purple-600 hover:bg-purple-700 text-white px-8 py-3 rounded-xl"
                  >
                    Finish Interview
                  </button>

                )}

              </div>

            )}

          </div>

        )}

      </div>

    </div>
  );
}

export default Interview;